version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"  # Внешний порт 27018 для избежания конфликтов
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: